id: issue-assignment-automation
namespace: autoaudit
description: AI-powered GitHub issue assignment based on comment analysis

inputs:
  - id: issue_number
    type: INT
    description: GitHub issue number
  - id: owner
    type: STRING
    description: Repository owner
  - id: repo
    type: STRING
    description: Repository name
  - id: comment_body
    type: STRING
    description: Comment text from user
  - id: commenter_username
    type: STRING
    description: GitHub username of commenter
  - id: commenter_id
    type: INT
    description: GitHub user ID of commenter
  - id: issue_title
    type: STRING
    description: Issue title
  - id: issue_body
    type: STRING
    description: Issue description
  - id: github_token
    type: STRING
    description: GitHub token for API calls
  - id: backend_api_url
    type: STRING
    description: Backend API URL
  - id: comment_created_at
    type: STRING
    description: Comment creation timestamp

tasks:
  - id: analyze_intent
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install openai
    env:
      OPENAI_API_KEY: "{{ secret('OPENAI_API_KEY') }}"
    script: |
      import os
      import json
      from openai import OpenAI
      
      client = OpenAI(api_key=os.environ['OPENAI_API_KEY'])
      
      # Prepare the analysis prompt
      prompt = f"""Analyze this GitHub issue comment to determine assignment intent.

      Issue Title: {{ inputs.issue_title }}
      Issue Description: {{ inputs.issue_body }}
      
      User @{{ inputs.commenter_username }} commented:
      {{ inputs.comment_body }}
      
      Your task: Determine if this comment indicates the user wants to be assigned to work on this issue.
      
      Return ONLY ONE of these three words:
      - ACCEPT: Comment shows intent to work on issue AND provides a valid approach/solution idea
      - REJECT: Comment shows intent to work on issue BUT lacks any approach or solution details
      - IGNORE: Comment is just discussion/info/question, NOT an assignment request
      
      Examples:
      - "I can fix this by updating the auth middleware" → ACCEPT
      - "I want to work on this" → REJECT (no approach)
      - "assign me" → REJECT (no approach)
      - "This is happening because of X" → IGNORE (just info)
      - "I'll refactor the parser module to handle this edge case" → ACCEPT
      
      Response (one word only):"""
      
      response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
          {"role": "system", "content": "You are an expert at analyzing GitHub issue comments. Respond with ONLY one word: ACCEPT, REJECT, or IGNORE."},
          {"role": "user", "content": prompt}
        ],
        temperature=0.1,
        max_tokens=10
      )
      
      decision = response.choices[0].message.content.strip().upper()
      print(decision)

  - id: route_decision
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ outputs.analyze_intent.outputs.out | trim | upper }}"
    cases:
      ACCEPT:
        - id: assign_issue
          type: io.kestra.plugin.core.http.Request
          uri: "{{ inputs.backend_api_url }}/api/repositories/{{ inputs.owner }}/{{ inputs.repo }}/issues/{{ inputs.issue_number }}/assign"
          method: POST
          headers:
            Content-Type: application/json
          body: |
            {
              "assignee": "{{ inputs.commenter_username }}",
              "githubToken": "{{ inputs.github_token }}"
            }
      
      REJECT:
        - id: request_more_details
          type: io.kestra.plugin.core.http.Request
          uri: "{{ inputs.backend_api_url }}/api/repositories/{{ inputs.owner }}/{{ inputs.repo }}/issues/{{ inputs.issue_number }}/comment"
          method: POST
          headers:
            Content-Type: application/json
          body: |
            {
              "comment": "@{{ inputs.commenter_username }} Thanks for your interest in working on this issue! 🙌\n\nTo help ensure successful assignment, could you please provide a brief explanation of your proposed approach to solving this issue? This helps us match contributors with tasks they're well-prepared for.\n\nFor example:\n- What changes do you plan to make?\n- Which files or components will you modify?\n- Any technical details about your solution?\n\nLooking forward to your response!",
              "githubToken": "{{ inputs.github_token }}"
            }
      
      IGNORE:
        - id: log_ignored
          type: io.kestra.plugin.core.log.Log
          message: "Comment from @{{ inputs.commenter_username }} was informational, no assignment action needed"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_SECRET_KEY') }}"
